version: '3.7'
services:
  web:
    image: node:lts-alpine
    volumes:
      - .:/usr/src/be
      - ./docker/local/tmp/node_modules:/usr/src/be/node_modules
    working_dir: /usr/src/be
    ports:
      - '10001:4000'
    command: ash -c 'yarn && yarn start:server'
    environment:
      FOO: BAR
    tty: true
    dns: 8.8.8.8
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --lower_case_table_names=1
    volumes:
      - ./docker/local/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/local/tmp/mysql:/var/lib/mysql
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: graphql_todo
